// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {
		int greaterThenHalf = 0;
		int lessThenHalf = 0;
		int numOfRuns = Integer.parseInt(args[0]);
		for (int i = 0; i < numOfRuns; i++) {
			if (Math.random() > 0.5) {
				greaterThenHalf = greaterThenHalf + 1;
			} else {
				lessThenHalf = lessThenHalf + 1;
			}
		}
		System.out.println("> 0.5: " + lessThenHalf + " times");
		System.out.println("<= 0.5: " + greaterThenHalf + " times");
		System.out.println("Ratio: " + (float) lessThenHalf / greaterThenHalf);
	}
}
